{{- range .Values.certs }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  commonName: {{ .commonName | quote }}
  secretName: {{ .secretName | quote }}
  dnsNames:
  {{- toYaml .dnsNames | nindent 2 }}
  issuerRef:
    group: cert-manager.io
    kind: {{ .issuerType }}
    name: {{ .issuerName | quote }}
{{- end }}