---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-cert
  namespace: gitea
spec:
  commonName: gitea.rgov.xyz
  secretName: gitea-cert
  dnsNames:
  - gitea.rgov.xyz
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: issuer-prod