gitea:
  config:
    migrations:
      ALLOWED_DOMAINS: github.com, *.github.com, *.rgov.xyz
      SKIP_TLS_VERIFY: true
    repository:
      ENABLE_PUSH_CREATE_ORG: true
      ENABLE_PUSH_CREATE_USER: true
    server:
      DOMAIN: git.rgov.xyz
      ROOT_URL: https://git.rgov.xyz
      SSH_DOMAIN: git-ssh.rgov.xyz
      SSH_PORT: "22"
    webhook:
      ALLOWED_HOST_LIST: '*.rgov.xyz'

persistence:
  size: 1Gi
  storageClass: longhorn

redis-cluster:
  cluster:
    nodes: 3
  persistence: 
    size: 1Gi

postgresql-ha:
  enabled: false

postgresql:
  enabled: true
  primary:
    persistence:
      size: 1Gi

image:
  rootless: true

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: git.rgov.xyz
      paths:
        - path: /
          pathType: Prefix
  tls: 
   - secretName: gitea-cert
     hosts:
       - git.rgov.xyz