---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: harbor
spec:
  commonName: harbor.rgov.xyz
  secretName: harbor-cert
  dnsNames:
  - harbor.rgov.xyz
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: issuer-prod