kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: elemental-harbor
  namespace: fleet-default
spec:
  repo: git@github.com:atoy3731/elemental-app-demo.git
  branch: main
  clientSecretName: private-key
  targets:
  - name: elemental-harbor
    clusterSelector:
      matchLabels:
        cluster: elemental-harbor
  paths:
  # Harbor
  - "./apps/harbor-cluster/harbor/certs"
  - "./apps/harbor-cluster/harbor/harbor"